// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdjscrevewcuqotkzcrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkanNjcmV2ZXdjdXFvdGt6Y3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MTA1MzcsImV4cCI6MjA2ODI4NjUzN30.UUC8Ngu7MHca25Ol73q53d2sM_dvrLKCbDrLYIeo_90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});